from app import db

class config(db.Model):
    """
    id                                      : unique identifier
    name                                    : human readable identifier
    hostname                                : hostname of authelia
    jwt_secret                              : jwt secret
                                            : Can be automatically generated with app.helpers.rndpwd.generate(count=63)
    default_redirection_url                 : Default Redirection URL `https://${hostname}`
                                              https://docs.authelia.com/configuration/miscellaneous.html#default-redirection-url
    auth_backend                            : Always file for now
    file_path:                              : Filepath of `/config/users_database.yml`

    password_algorithm                      : Algorithm to use for password hash `argon2`
    password_algorithm_variant              : Variant of argon2 `argon2id`
    password_iterations                     : number of hash iterations `1`
    password_salt_length                    : length of salt `16`
    password_parallelism                    : Parallelism `8`
    password_memory                         : Blocks this much RAM.  TUNE THIS!!! `512`
 
    access_control_default                  : Default Access Control Policy `deny`
 
    session_name                            : authelia_session
    session_secret                          : Can be automaticall generated by app.helpers.rndpwd.generate(count=63)
    session_expiration                      : Expiration time (in seconds) `3600`
    session_inactivity                      : Inactivity Time (in seconds) `300`
    session_domain                          : should match hostname

    regulation_max_retries                  : `3`
    regulation_find_time                    : `120`
    regulation_ban_time                     : `300`

    storage_local_path:                     : `/config/db.sqlite3`
    
    notifier_smtp_enable                    : `true`
    notifier_smtp_host                      : smtp hostname
    notifier_smtp_port                      : `465`
    notifier_smtp_timeout                   : `10s`
    notifier_smtp_username                  : username
    notifier_smtp_password                  : password
    notifier_smtp_sender                    : send email address
    notifier_smtp_identifier                : name for smtp server
    notifier_smtp_subject                   : `"[Authelia] {title}"`
    notifier_smtp_startup_check_address     : test.authelia.com
    notifier_smtp_disable_require_tls       : `false`
    notifier_smtp_disable_starttls          : `true`
    notifier_smtp_disable_html_emails       : `false`
    notifier_smtp_tls_server_name           : smtp server
    notifier_smtp_tls_skip_verify           : `true`

    notifier_filesystem_enable              : `false`
    notifier_filesystem_filename            : `/config/filesystem_notifier.txt`
    """

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50),unique=True)
    hostname = db.Column(db.String(250),unique=True)
    jwt_secret = db.Column(db.String(64))
    default_redirection_url = db.Column(db.String(500))
    auth_backend = db.Column(db.String(20))
    file_path = db.Column(db.String(500))
    password_algorithm = db.Column(db.String(10))
    password_algorithm_variant = db.Column(db.String(10))
    password_iterations = db.Column(db.Integer)
    password_salt_length = db.Column(db.Integer)
    password_parallelism = db.Column(db.Integer)
    password_memory = db.Column(db.Integer)
    access_control_default = db.Column(db.String(10))
    session_name = db.Column(db.String(32))
    session_secret = db.Column(db.String(64))
    session_expiration = db.Column(db.Integer)
    session_inactivity = db.Column(db.Integer)
    session_domain = db.Column(db.String(250))
    regulation_max_retries = db.Column(db.Integer)
    regulation_find_time = db.Column(db.Integer)
    regulation_ban_time = db.Column(db.Integer)
    storage_local_path = db.Column(db.String(128))
    notifier_smtp_enable = db.Column(db.String(5))
    notifier_smtp_host = db.Column(db.String(250))
    notifier_smtp_port = db.Column(db.Integer)
    notifier_smtp_timeout = db.Column(db.String(30))
    notifier_smtp_username = db.Column(db.String(256))
    notifier_smtp_password = db.Column(db.String(256))
    notifier_smtp_sender = db.Column(db.String(256))
    notifier_smtp_identifier = db.Column(db.String(128))
    notifier_smtp_subject = db.Column(db.String(256))
    notifier_smtp_startup_check_address = db.Column(db.String(256))
    notifier_smtp_disable_requre_tls = db.Column(db.String(5))
    notifier_smtp_disable_starttls = db.Column(db.String(5))
    notifier_smtp_disable_html_emails = db.Column(db.String(5))
    notifier_smtp_tls_server_name = db.Column(db.String(250))
    notifier_smtp_tls_skip_verify = db.Column(db.String(250))
    notifier_filesystem_enable = db.Column(db.String(5))
    notifier_filesystem_filename = db.Column(db.String(512))
